# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dee071a24fa259c4e34d55cf5642c57e2146e76eaa84764d436d04d4ff9603b1ebe304cde26856a16663911704d950efe5aaba5b351df403493a7c913f524df

test:
  secret_key_base: be0147b92ea61f7f00a4564c3cb7fcf02834a1addc24c075d33e1ad1fc2f71da84f41a59e9e6cb837e739e95de250abb22cba63f1e8d3447f4ef06898ad3fd8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
